// Curated oxlint rule set, initially derived from @antfu/eslint-config@9.0.0
// (mapped onto oxlint@1.70.0's rules). This is now a plain, hand-maintained
// source file — edit rules/severities freely.

export interface RuleGroup {
  /** oxlint built-in plugins these rules belong to */
  plugins: string[]
  /** glob(s) to scope these rules; `null` = applied globally (top-level rules) */
  files: string[] | null
  /** oxlint rule name -> severity or [severity, ...options] */
  rules: Record<string, unknown>
}

/** antfu's rule choices, grouped by oxlint plugin family, filtered to rules oxlint implements. */
export const RULE_GROUPS = {
  js: {
    plugins: ['eslint'],
    files: null,
    rules: {
      'accessor-pairs': [
        'error',
        {
          enforceForClassMembers: true,
          setWithoutGet: true,
        },
      ],
      'array-callback-return': 'error',
      'block-scoped-var': 'error',
      'constructor-super': 'off',
      'default-case-last': 'error',
      'eqeqeq': ['error', 'smart'],
      'new-cap': [
        'error',
        {
          capIsNew: false,
          newIsCap: true,
          properties: true,
        },
      ],
      'no-alert': 'off',
      'no-array-constructor': 'off',
      'no-async-promise-executor': 'error',
      'no-caller': 'error',
      'no-case-declarations': 'error',
      'no-class-assign': 'off',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': ['error', 'always'],
      'no-console': 'off',
      'no-const-assign': 'off',
      'no-control-regex': 'error',
      'no-debugger': 'error',
      'no-delete-var': 'error',
      'no-dupe-class-members': 'off',
      'no-dupe-keys': 'off',
      'no-duplicate-case': 'error',
      'no-empty': [
        'error',
        {
          allowEmptyCatch: true,
        },
      ],
      'no-empty-character-class': 'off',
      'no-empty-pattern': 'error',
      'no-eval': 'error',
      'no-ex-assign': 'error',
      'no-extend-native': 'error',
      'no-extra-bind': 'error',
      'no-extra-boolean-cast': 'error',
      'no-fallthrough': 'error',
      'no-func-assign': 'off',
      'no-global-assign': 'error',
      'no-implied-eval': 'error',
      'no-import-assign': 'off',
      'no-invalid-regexp': 'off',
      'no-irregular-whitespace': 'error',
      'no-iterator': 'error',
      'no-labels': 'off',
      'no-lone-blocks': 'off',
      'no-loss-of-precision': 'error',
      'no-misleading-character-class': 'error',
      'no-multi-str': 'error',
      'no-new': 'error',
      'no-new-func': 'error',
      'no-new-native-nonconstructor': 'off',
      'no-new-wrappers': 'error',
      'no-obj-calls': 'off',
      'no-proto': 'error',
      'no-prototype-builtins': 'error',
      'no-redeclare': 'off',
      'no-regex-spaces': 'error',
      'no-restricted-globals': [
        'error',
        {
          message: 'Use `globalThis` instead.',
          name: 'global',
        },
        {
          message: 'Use `globalThis` instead.',
          name: 'self',
        },
      ],
      'no-restricted-properties': [
        'error',
        {
          message: 'Use `Object.getPrototypeOf` or `Object.setPrototypeOf` instead.',
          property: '__proto__',
        },
        {
          message: 'Use `Object.defineProperty` instead.',
          property: '__defineGetter__',
        },
        {
          message: 'Use `Object.defineProperty` instead.',
          property: '__defineSetter__',
        },
        {
          message: 'Use `Object.getOwnPropertyDescriptor` instead.',
          property: '__lookupGetter__',
        },
        {
          message: 'Use `Object.getOwnPropertyDescriptor` instead.',
          property: '__lookupSetter__',
        },
      ],
      'no-self-assign': [
        'error',
        {
          props: true,
        },
      ],
      'no-self-compare': 'error',
      'no-sequences': 'error',
      'no-shadow-restricted-names': 'error',
      'no-sparse-arrays': 'error',
      'no-template-curly-in-string': 'error',
      'no-this-before-super': 'off',
      'no-throw-literal': 'error',
      'no-unexpected-multiline': 'error',
      'no-unmodified-loop-condition': 'error',
      'no-unneeded-ternary': [
        'error',
        {
          defaultAssignment: false,
        },
      ],
      'no-unreachable': 'off',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'off',
      'no-unused-expressions': 'off',
      'no-unused-vars': 'off',
      'no-use-before-define': 'off',
      'no-useless-backreference': 'off',
      'no-useless-call': 'error',
      'no-useless-catch': 'error',
      'no-useless-computed-key': 'error',
      'no-useless-constructor': 'off',
      'no-useless-rename': 'error',
      'no-useless-return': 'error',
      'no-var': 'error',
      'no-with': 'off',
      'object-shorthand': [
        'error',
        'always',
        {
          avoidQuotes: true,
          ignoreConstructors: false,
        },
      ],
      'prefer-arrow-callback': [
        'error',
        {
          allowNamedFunctions: false,
          allowUnboundThis: true,
        },
      ],
      'prefer-const': 'error',
      'prefer-exponentiation-operator': 'error',
      'prefer-promise-reject-errors': 'error',
      'prefer-regex-literals': 'error',
      'prefer-rest-params': 'error',
      'prefer-spread': 'error',
      'prefer-template': 'error',
      'symbol-description': 'error',
      'unicode-bom': 'off',
      'use-isnan': [
        'error',
        {
          enforceForIndexOf: true,
          enforceForSwitchCase: true,
        },
      ],
      'valid-typeof': [
        'error',
        {
          requireStringLiterals: true,
        },
      ],
      'vars-on-top': 'error',
      'yoda': ['error', 'never'],
      'getter-return': 'off',
      'no-setter-return': 'off',
      'no-unused-labels': 'off',
    },
  },
  node: {
    plugins: ['node'],
    files: null,
    rules: {
      'node/handle-callback-err': ['error', '^(err|error)$'],
      'node/no-exports-assign': 'error',
      'node/no-new-require': 'error',
      'node/no-path-concat': 'error',
    },
  },
  jsdoc: {
    plugins: ['jsdoc'],
    files: null,
    rules: {
      'jsdoc/check-access': 'warn',
      'jsdoc/check-property-names': 'warn',
      'jsdoc/empty-tags': 'warn',
      'jsdoc/implements-on-classes': 'warn',
      'jsdoc/no-defaults': 'warn',
      'jsdoc/require-param-name': 'warn',
      'jsdoc/require-property': 'warn',
      'jsdoc/require-property-description': 'warn',
      'jsdoc/require-property-name': 'warn',
      'jsdoc/require-returns-description': 'warn',
    },
  },
  imports: {
    plugins: ['import'],
    files: null,
    rules: {
      'import/consistent-type-specifier-style': ['error', 'prefer-top-level'],
      'import/first': 'error',
      'import/no-duplicates': 'error',
      'import/no-mutable-exports': 'error',
      'import/no-named-default': 'error',
      'import/newline-after-import': [
        'error',
        {
          count: 1,
        },
      ],
    },
  },
  unicorn: {
    plugins: ['unicorn'],
    files: null,
    rules: {
      'unicorn/consistent-empty-array-spread': 'error',
      'unicorn/error-message': 'error',
      'unicorn/escape-case': 'error',
      'unicorn/new-for-builtins': 'error',
      'unicorn/no-instanceof-builtins': 'error',
      'unicorn/no-new-array': 'error',
      'unicorn/no-new-buffer': 'error',
      'unicorn/number-literal-case': 'error',
      'unicorn/prefer-dom-node-text-content': 'error',
      'unicorn/prefer-includes': 'error',
      'unicorn/prefer-node-protocol': 'error',
      'unicorn/prefer-number-properties': 'error',
      'unicorn/prefer-string-starts-ends-with': 'error',
      'unicorn/prefer-type-error': 'error',
      'unicorn/throw-new-error': 'error',
    },
  },
  ts: {
    plugins: ['typescript'],
    files: ['**/*.{ts,tsx,mts,cts}'],
    rules: {
      'typescript/ban-ts-comment': [
        'error',
        {
          'ts-expect-error': 'allow-with-description',
        },
      ],
      'typescript/no-array-constructor': 'error',
      'typescript/no-duplicate-enum-values': 'error',
      'typescript/no-dynamic-delete': 'off',
      'typescript/no-empty-object-type': [
        'error',
        {
          allowInterfaces: 'always',
        },
      ],
      'typescript/no-explicit-any': 'off',
      'typescript/no-extra-non-null-assertion': 'error',
      'typescript/no-extraneous-class': 'off',
      'typescript/no-invalid-void-type': 'off',
      'typescript/no-misused-new': 'error',
      'typescript/no-namespace': 'off',
      'typescript/no-non-null-asserted-nullish-coalescing': 'error',
      'typescript/no-non-null-asserted-optional-chain': 'error',
      'typescript/no-non-null-assertion': 'off',
      'typescript/no-require-imports': 'off',
      'typescript/no-this-alias': 'error',
      'typescript/no-unnecessary-type-constraint': 'error',
      'typescript/no-unsafe-declaration-merging': 'error',
      'typescript/no-unsafe-function-type': 'error',
      'typescript/no-unused-expressions': 'off',
      'typescript/no-unused-vars': 'off',
      'typescript/no-useless-constructor': 'off',
      'typescript/no-wrapper-object-types': 'error',
      'typescript/prefer-as-const': 'error',
      'typescript/prefer-literal-enum-member': 'error',
      'typescript/prefer-namespace-keyword': 'error',
      'typescript/triple-slash-reference': 'off',
      'typescript/unified-signatures': 'off',
      'typescript/consistent-type-definitions': ['error', 'interface'],
      'typescript/consistent-type-imports': 'off',
      'typescript/method-signature-style': ['error', 'property'],
      'typescript/no-dupe-class-members': 'error',
      'typescript/no-import-type-side-effects': 'error',
      'typescript/no-redeclare': 'off',
      'typescript/no-use-before-define': 'off',
      'typescript/explicit-function-return-type': 'off',
    },
  },
  test: {
    plugins: ['vitest'],
    files: [
      '**/*.{test,test-d,spec,bench,benchmark}.{js,mjs,cjs,jsx,ts,mts,cts,tsx}',
      '**/__tests__/**/*.{js,mjs,cjs,jsx,ts,mts,cts,tsx}',
    ],
    rules: {
      'vitest/consistent-test-it': [
        'error',
        {
          fn: 'it',
          withinDescribe: 'it',
        },
      ],
      'vitest/no-identical-title': 'error',
      'vitest/no-import-node-test': 'error',
      'vitest/prefer-hooks-in-order': 'error',
      'vitest/prefer-lowercase-title': 'error',
    },
  },
  vue: {
    plugins: ['vue'],
    files: ['**/*.vue'],
    rules: {
      'vue/no-arrow-functions-in-watch': 'error',
      'vue/no-computed-properties-in-data': 'error',
      'vue/no-deprecated-data-object-declaration': 'error',
      'vue/no-deprecated-delete-set': 'error',
      'vue/no-deprecated-destroyed-lifecycle': 'error',
      'vue/no-deprecated-events-api': 'error',
      'vue/no-deprecated-model-definition': 'error',
      'vue/no-deprecated-props-default-this': 'error',
      'vue/no-deprecated-vue-config-keycodes': 'error',
      'vue/no-dupe-keys': 'off',
      'vue/no-export-in-script-setup': 'error',
      'vue/no-expose-after-await': 'error',
      'vue/no-lifecycle-after-await': 'error',
      'vue/no-reserved-component-names': 'error',
      'vue/no-reserved-keys': 'error',
      'vue/no-reserved-props': 'error',
      'vue/no-shared-component-data': 'error',
      'vue/no-side-effects-in-computed-properties': 'error',
      'vue/no-watch-after-await': 'error',
      'vue/prefer-import-from-vue': 'error',
      'vue/require-prop-type-constructor': 'error',
      'vue/require-render-return': 'error',
      'vue/require-slots-as-functions': 'error',
      'vue/return-in-computed-property': 'error',
      'vue/return-in-emits-validator': 'error',
      'vue/valid-define-emits': 'error',
      'vue/valid-define-options': 'error',
      'vue/valid-define-props': 'error',
      'vue/valid-next-tick': 'error',
      'vue/component-definition-name-casing': 'warn',
      'vue/prop-name-casing': ['error', 'camelCase'],
      'vue/require-default-prop': 'off',
      'vue/require-prop-types': 'off',
      'vue/no-multiple-slot-args': 'warn',
      'vue/no-required-prop-with-default': 'warn',
    },
  },
} satisfies Record<string, RuleGroup>

export type GroupKey = keyof typeof RULE_GROUPS

/** antfu's perfectionist rules — loaded via oxlint jsPlugins (eslint-plugin-perfectionist). */
export const PERFECTIONIST_RULES: Record<string, unknown> = {
  'perfectionist/sort-exports': [
    'error',
    {
      order: 'asc',
      type: 'natural',
    },
  ],
  'perfectionist/sort-imports': [
    'error',
    {
      groups: [
        'type-import',
        ['type-parent', 'type-sibling', 'type-index', 'type-internal'],
        'value-builtin',
        'value-external',
        'value-internal',
        ['value-parent', 'value-sibling', 'value-index'],
        'side-effect',
        'ts-equals-import',
        'unknown',
      ],
      newlinesBetween: 'ignore',
      newlinesInside: 'ignore',
      order: 'asc',
      type: 'natural',
    },
  ],
  'perfectionist/sort-named-exports': [
    'error',
    {
      order: 'asc',
      type: 'natural',
    },
  ],
  'perfectionist/sort-named-imports': [
    'error',
    {
      order: 'asc',
      type: 'natural',
    },
  ],
}

/** antfu rules that map to a real oxlint plugin but the specific rule is not implemented yet. */
export const GAPS: string[] = [
  'dot-notation',
  'jsdoc/check-alignment',
  'jsdoc/check-param-names',
  'jsdoc/check-types',
  'jsdoc/multiline-blocks',
  'jsdoc/no-multi-asterisks',
  'jsdoc/require-returns-check',
  'jsdoc/require-yields-check',
  'no-dupe-args',
  'no-new-symbol',
  'no-octal',
  'no-octal-escape',
  'no-restricted-syntax',
  'no-undef',
  'no-undef-init',
  'no-unreachable-loop',
  'node/no-deprecated-api',
  'node/prefer-global/buffer',
  'node/prefer-global/process',
  'node/process-exit-as-throw',
  'one-var',
  'test/no-only-tests',
  'vue/array-bracket-spacing',
  'vue/arrow-spacing',
  'vue/attribute-hyphenation',
  'vue/attributes-order',
  'vue/block-order',
  'vue/block-spacing',
  'vue/block-tag-newline',
  'vue/brace-style',
  'vue/comma-dangle',
  'vue/comma-spacing',
  'vue/comma-style',
  'vue/comment-directive',
  'vue/component-name-in-template-casing',
  'vue/component-options-name-casing',
  'vue/component-tags-order',
  'vue/custom-event-name-casing',
  'vue/define-macros-order',
  'vue/dot-location',
  'vue/dot-notation',
  'vue/eqeqeq',
  'vue/first-attribute-linebreak',
  'vue/html-closing-bracket-newline',
  'vue/html-closing-bracket-spacing',
  'vue/html-comment-content-spacing',
  'vue/html-end-tags',
  'vue/html-indent',
  'vue/html-quotes',
  'vue/html-self-closing',
  'vue/jsx-uses-vars',
  'vue/key-spacing',
  'vue/keyword-spacing',
  'vue/max-attributes-per-line',
  'vue/multi-word-component-names',
  'vue/multiline-html-element-content-newline',
  'vue/mustache-interpolation-spacing',
  'vue/no-async-in-computed-properties',
  'vue/no-child-content',
  'vue/no-deprecated-dollar-listeners-api',
  'vue/no-deprecated-dollar-scopedslots-api',
  'vue/no-deprecated-filter',
  'vue/no-deprecated-functional-template',
  'vue/no-deprecated-html-element-is',
  'vue/no-deprecated-inline-template',
  'vue/no-deprecated-router-link-tag-prop',
  'vue/no-deprecated-scope-attribute',
  'vue/no-deprecated-slot-attribute',
  'vue/no-deprecated-slot-scope-attribute',
  'vue/no-deprecated-v-bind-sync',
  'vue/no-deprecated-v-is',
  'vue/no-deprecated-v-on-native-modifier',
  'vue/no-deprecated-v-on-number-modifiers',
  'vue/no-dupe-v-else-if',
  'vue/no-duplicate-attributes',
  'vue/no-empty-pattern',
  'vue/no-irregular-whitespace',
  'vue/no-lone-template',
  'vue/no-loss-of-precision',
  'vue/no-multi-spaces',
  'vue/no-mutating-props',
  'vue/no-parsing-error',
  'vue/no-ref-as-operand',
  'vue/no-restricted-syntax',
  'vue/no-restricted-v-bind',
  'vue/no-setup-props-reactivity-loss',
  'vue/no-spaces-around-equal-signs-in-attribute',
  'vue/no-sparse-arrays',
  'vue/no-template-key',
  'vue/no-template-shadow',
  'vue/no-textarea-mustache',
  'vue/no-unused-components',
  'vue/no-unused-refs',
  'vue/no-unused-vars',
  'vue/no-use-computed-property-like-method',
  'vue/no-use-v-if-with-v-for',
  'vue/no-useless-template-attributes',
  'vue/no-useless-v-bind',
  'vue/no-v-for-template-key-on-child',
  'vue/no-v-html',
  'vue/no-v-text-v-html-on-component',
  'vue/object-curly-newline',
  'vue/object-curly-spacing',
  'vue/object-property-newline',
  'vue/object-shorthand',
  'vue/one-component-per-file',
  'vue/operator-linebreak',
  'vue/order-in-components',
  'vue/padding-line-between-blocks',
  'vue/prefer-separate-static-class',
  'vue/prefer-template',
  'vue/quote-props',
  'vue/require-component-is',
  'vue/require-explicit-emits',
  'vue/require-toggle-inside-transition',
  'vue/require-v-for-key',
  'vue/require-valid-default-prop',
  'vue/singleline-html-element-content-newline',
  'vue/space-in-parens',
  'vue/space-infix-ops',
  'vue/space-unary-ops',
  'vue/template-curly-spacing',
  'vue/this-in-template',
  'vue/use-v-on-exact',
  'vue/v-bind-style',
  'vue/v-on-event-hyphenation',
  'vue/v-on-style',
  'vue/v-slot-style',
  'vue/valid-attribute-name',
  'vue/valid-template-root',
  'vue/valid-v-bind',
  'vue/valid-v-cloak',
  'vue/valid-v-else',
  'vue/valid-v-else-if',
  'vue/valid-v-for',
  'vue/valid-v-html',
  'vue/valid-v-if',
  'vue/valid-v-is',
  'vue/valid-v-memo',
  'vue/valid-v-model',
  'vue/valid-v-on',
  'vue/valid-v-once',
  'vue/valid-v-pre',
  'vue/valid-v-show',
  'vue/valid-v-slot',
  'vue/valid-v-text',
]

export const GEN_META = {
  generatedFrom: {
    antfu: '9.0.0',
    oxlint: '1.70.0',
  },
  oxlintRuleCount: 813,
  antfuRuleCount: 690,
  keptCount: 210,
  perfectionistCount: 4,
  gapCount: 146,
  droppedByPrefix: {
    'antfu/': 17,
    'unused-imports/': 5,
    'eslint-comments/': 5,
    'command/': 1,
    'e18e/': 18,
    'style/': 70,
    'regexp/': 60,
    'jsonc/': 39,
    'yaml/': 18,
    'toml/': 19,
    'markdown/': 17,
  },
  optionsStripped: [],
} as const
